version: '3.7'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "S1@Serv#sw2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1439:1433"
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./sql/01.sql:/tmp/01.sql
      - ./sql/02.sql:/tmp/02.sql
      - ./init.sh:/tmp/init.sh
    command: /bin/bash ./tmp/init.sh
  